apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketdex-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rocketdex
  template:
    metadata:
      labels:
        app: rocketdex
    spec:
      containers:
      - name: rocketdex
        image: ghcr.io/moisieievvasya/moisieiev-gh-actions-workshop:ed6dc84
        ports:
        - containerPort: 8080